In [1]:
import numpy as np

In [5]:
my_array = np.array([1,302032,322423423,2423423432424242,424234232232432])
my_array.size*my_array.itemsize

40

In [6]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [7]:
my_vector = np.arange(10, 50)
my_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
reversed_v = my_vector[::-1]
reversed_v

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
my_vals = np.arange(9)
my_vals

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
my_matrix = np.reshape(my_vals, (3,3))
my_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
array_eight = np.array([1,2,0,0,4,0])
array_eight

array([1, 2, 0, 0, 4, 0])

In [15]:
np.nonzero(array_eight)

(array([0, 1, 4]),)

In [16]:
mat_eye = np.eye(3)
mat_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
my_matr = np.tile(np.arange(5), (5,1))
my_matr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [24]:
vec = np.linspace(0, 1, 12)[1:-1]
vec

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [25]:
vect = np.random.rand(10)
sorted_vect = np.sort(vect)
sorted_vect

array([0.17197726, 0.26683869, 0.26984696, 0.4104909 , 0.60774585,
       0.6236989 , 0.68325136, 0.69017439, 0.80708268, 0.90791093])

In [27]:
float_array = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)

float_array = float_array.astype(np.int32)
float_array

array([1, 2, 3, 4], dtype=int32)

In [29]:
matr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_mean = np.mean(matr, axis=1)

res_matr = matr - row_mean[:, np.newaxis]


In [32]:
# twod_array = ([1,2,3],
#             [4,5,6],
#            [7,8,9])
# nsort = np.argsort(twod_array)
# nsort

TypeError: tuple indices must be integers or slices, not tuple

In [35]:
input_array = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
input_array[0], input_array[1] = input_array[1], input_array[0]
input_array


[[3, 4, 5], [0, 1, 2], [6, 7, 8]]

In [36]:
new_array = np.array([1,2,3,4,5,6,7])
np.repeat(len(new_array), new_array)

ValueError: operands could not be broadcast together with shape (1,) (7,)