In [1]:
import numpy as np

In [2]:
import pandas as pd

In [5]:
sales = [0, 5, 155,0, 518, 9, 1827, 616, 317, 325]
sales_series = pd.Series(sales, name="Sales")

In [6]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       9
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [7]:
sales_series.values

array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

In [8]:
sales_series.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
sales_series.name

'Sales'

In [10]:
sales_series.dtype

dtype('int64')

In [11]:
sales_series.astype("bool")

0    False
1     True
2     True
3    False
4     True
5     True
6     True
7     True
8     True
9     True
Name: Sales, dtype: bool

In [12]:
sales_series.astype("float")

0       0.0
1       5.0
2     155.0
3       0.0
4     518.0
5       9.0
6    1827.0
7     616.0
8     317.0
9     325.0
Name: Sales, dtype: float64

In [13]:
oil = pd.read_csv("./oil.csv").dropna()
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])
oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [14]:
oil_series = pd.Series(oil_array, name="oil_prices")
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: oil_prices, Length: 100, dtype: float64

In [15]:
oil_series.mean()

51.128299999999996

In [17]:
oil_series.astype("int").values.mean()

50.66

In [18]:
sales_series

0       0
1       5
2     155
3       0
4     518
5       9
6    1827
7     616
8     317
9     325
Name: Sales, dtype: int64

In [21]:
sales_series[2:5].mean()

224.33333333333334

In [34]:
items = ["coffee", "bananas", "tea","coconut", "sugar"]
sales_items = sales_series[:5]
sales_items.index=items
sales_items

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [31]:
# pd_sales = pd.Series(sales_items, index=items, name="Sales_Item")
# pd_sales

In [35]:
sales_items["tea"]

155

In [37]:
sales_items["bananas":"coconut"]

bananas      5
tea        155
coconut      0
Name: Sales, dtype: int64

In [38]:
sales_items[2]

155

In [40]:
#loc v iloc

In [41]:
items = ["coffee", "coffee", "tea","coconut", "sugar"]
sales_items.index = items
sales_items

coffee       0
coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [42]:
sales_items["coffee"]

coffee    0
coffee    5
Name: Sales, dtype: int64

In [43]:
sales_items.reset_index()

index  Sales
0   coffee      0
1   coffee      5
2      tea    155
3  coconut      0
4    sugar    518

In [44]:
sales_items.reset_index(drop=True)

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.

Then, take the mean of the first 10 and last 10 prices of the series.

Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

In [45]:
oil = pd.read_csv("./oil.csv").dropna()
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [46]:
pd.Series("oil")

0    oil
dtype: object

In [53]:
dates = pd.Series(oil["date"].iloc[1000:1100])
dates

2016-12-20    2016-12-20
2016-12-21    2016-12-21
2016-12-22    2016-12-22
2016-12-23    2016-12-23
2016-12-27    2016-12-27
                 ...    
2017-05-09    2017-05-09
2017-05-10    2017-05-10
2017-05-11    2017-05-11
2017-05-12    2017-05-12
2017-05-15    2017-05-15
Name: date, Length: 100, dtype: object

In [54]:
oil_series.index = dates

In [55]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prices, Length: 100, dtype: float64

In [56]:
oil_series[:10].mean()

52.765

In [59]:
oil_series.iloc[-10].mean()

47.65

In [62]:
oil_series.loc["2017-01-01": "2017-01-07"].reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: oil_prices, dtype: float64

FILTERING SERIES


In [63]:
sales = [0, 5, 155,0, 518, 9, 1827, 616, 317, 325]
sales_series = pd.Series(sales, name="Sales")

In [65]:
sales_series = sales_series[:5]
sales_series

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [66]:
sales_series.loc[sales_series > 0]

1      5
2    155
4    518
Name: Sales, dtype: int64

In [67]:
sales_series > 0


0    False
1     True
2     True
3    False
4     True
Name: Sales, dtype: bool

In [70]:
sales_series.index = items
mask = (sales_series > 0) & (sales_series.index == 'coffee')
sales_series.loc[mask]

coffee    5
Name: Sales, dtype: int64

In [71]:
sales_series ==5
##numpy

coffee     False
coffee      True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [72]:
sales_series.eq(5)
##pandas

coffee     False
coffee      True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [78]:
sales_series.index.isin(["coffee", "tea"])

array([ True,  True,  True, False, False])

In [79]:
~sales_series.index.isin(["coffee", "tea"])

array([False, False, False,  True,  True])

Sorting Series


In [80]:
sales_series.sort_values(ascending=False)

sugar      518
tea        155
coffee       5
coffee       0
coconut      0
Name: Sales, dtype: int64

In [81]:
sales_series.sort_index(ascending=False)

tea        155
sugar      518
coffee       0
coffee       5
coconut      0
Name: Sales, dtype: int64

In [82]:
sales_series.sort_index(ascending=True)

coconut      0
coffee       0
coffee       5
sugar      518
tea        155
Name: Sales, dtype: int64

Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [83]:
dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]

In [84]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prices, Length: 100, dtype: float64

In [92]:
oil_series.sort_values(ascending=True).iloc[0:9]

date
2017-05-04    45.55
2017-05-09    45.84
2017-05-05    46.23
2017-05-08    46.46
2017-03-23    47.00
2017-03-21    47.02
2017-03-27    47.02
2017-03-14    47.24
2017-05-10    47.28
Name: oil_prices, dtype: float64

In [96]:
oil_series.index[0:9].sort_values(ascending=True)

Index(['2016-12-20', '2016-12-21', '2016-12-22', '2016-12-23', '2016-12-27',
       '2016-12-28', '2016-12-29', '2016-12-30', '2017-01-03'],
      dtype='object', name='date')

In [100]:
#the mask method is a filtering method
mask = (oil_series <= 50) & (oil_series.index.isin(dates))
oil_series.loc[mask]

date
2017-03-21    47.02
2017-05-03    47.79
Name: oil_prices, dtype: float64

In [101]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prices, Length: 100, dtype: float64

In [108]:
oil_series[oil_series.index.str[5:7] == "03"].sum().round()

1135.0

In [112]:
sales = [0, 5, 155, np.nan, 518]
my_sales = pd.Series(sales)
my_sales

0      0.0
1      5.0
2    155.0
3      NaN
4    518.0
dtype: float64

In [113]:
my_sales +2

0      2.0
1      7.0
2    157.0
3      NaN
4    520.0
dtype: float64

In [114]:
my_sales.add(2)

0      2.0
1      7.0
2    157.0
3      NaN
4    520.0
dtype: float64

In [115]:
my_sales.add(2, fill_value=0)

0      2.0
1      7.0
2    157.0
3      2.0
4    520.0
dtype: float64

In [116]:
my_sales.astype("float").fillna(my_sales.mean())

0      0.0
1      5.0
2    155.0
3    169.5
4    518.0
dtype: float64

In [117]:
min_sale = my_sales.mean()
my_sales.fillna(min_sale)

0      0.0
1      5.0
2    155.0
3    169.5
4    518.0
dtype: float64

In [120]:
oil_series.isna().count()

100

In [121]:
med_sale = oil_series.mean()
oil_series.fillna(med_sale)
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...  
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil_prices, Length: 100, dtype: float64

In [123]:
# apply method
clean_wholesale = pd.Series([3.99, 5.99, 22.99, 7.99, 33.99])
clean_wholesale

0     3.99
1     5.99
2    22.99
3     7.99
4    33.99
dtype: float64

In [124]:
def discount(price):
    if price > 20:
        return round(price * 0.9, 2)
    return price

In [126]:
clean_wholesale.apply(discount)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [127]:
clean_wholesale.where(clean_wholesale <=20, round(clean_wholesale*.9, 2), inplace=False)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64

In [128]:

clean_wholesale.where(~(clean_wholesale >20), round(clean_wholesale*.9, 2), inplace=False)

0     3.99
1     5.99
2    20.69
3     7.99
4    30.59
dtype: float64