In [1]:
import numpy as np

numpy into

In [2]:
my_list = [x*10 for x in range(1,11)]

In [3]:
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [7]:
my_list = np.array(my_list)

In [8]:
print(f"ndim: {my_list.ndim}")

ndim: 1


In [15]:
my_a = np.arange(10,101, 10).reshape(5,2)

In [16]:
my_a

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [17]:
my_lin_array = np.linspace(10,100,10).reshape(5,2)

In [18]:
my_lin_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])


* prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
* Before we do that,

*Add a 5 dollar shipping fee to each price. Call this array total.

* Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from random_array, reshape it to one dimension. Call this discount_pct.
* Subtract discount_pct FROM 1, store this in pct_owed.
* Multiply pct_owed by total to get the final amount owed.

In [21]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [27]:
array_total = prices + 5

In [28]:
array_total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])